/*
 * generated by Xtext 2.25.0
 */
package org.osarenogae.fta.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.osarenogae.fta.ui.internal.FtaActivator;

public class FaultTreeUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return FtaActivator.getInstance().getInjector("org.osarenogae.fta.FaultTree");
	}

}
