/**
 * generated by Xtext 2.25.0
 */
package org.osarenogae.fta.faultTree;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Basic Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.osarenogae.fta.faultTree.BasicEvent#getDescription <em>Description</em>}</li>
 * </ul>
 *
 * @see org.osarenogae.fta.faultTree.FaultTreePackage#getBasicEvent()
 * @model
 * @generated
 */
public interface BasicEvent extends Tree
{
  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.osarenogae.fta.faultTree.FaultTreePackage#getBasicEvent_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.osarenogae.fta.faultTree.BasicEvent#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

} // BasicEvent
