/**
 * generated by Xtext 2.25.0
 */
package org.osarenogae.fta.faultTree;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>begin</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.osarenogae.fta.faultTree.begin#getFault <em>Fault</em>}</li>
 * </ul>
 *
 * @see org.osarenogae.fta.faultTree.FaultTreePackage#getbegin()
 * @model
 * @generated
 */
public interface begin extends EObject
{
  /**
   * Returns the value of the '<em><b>Fault</b></em>' containment reference list.
   * The list contents are of type {@link org.osarenogae.fta.faultTree.Tree}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fault</em>' containment reference list.
   * @see org.osarenogae.fta.faultTree.FaultTreePackage#getbegin_Fault()
   * @model containment="true"
   * @generated
   */
  EList<Tree> getFault();

} // begin
