/**
 * generated by Xtext 2.25.0
 */
package org.osarenogae.fta.faultTree;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.osarenogae.fta.faultTree.FaultTreeFactory
 * @model kind="package"
 * @generated
 */
public interface FaultTreePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "faultTree";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.osarenogae.org/fta/FaultTree";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "faultTree";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  FaultTreePackage eINSTANCE = org.osarenogae.fta.faultTree.impl.FaultTreePackageImpl.init();

  /**
   * The meta object id for the '{@link org.osarenogae.fta.faultTree.impl.FaultTreeModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.osarenogae.fta.faultTree.impl.FaultTreeModelImpl
   * @see org.osarenogae.fta.faultTree.impl.FaultTreePackageImpl#getFaultTreeModel()
   * @generated
   */
  int FAULT_TREE_MODEL = 0;

  /**
   * The feature id for the '<em><b>Fault Tree</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAULT_TREE_MODEL__FAULT_TREE = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAULT_TREE_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.osarenogae.fta.faultTree.impl.beginImpl <em>begin</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.osarenogae.fta.faultTree.impl.beginImpl
   * @see org.osarenogae.fta.faultTree.impl.FaultTreePackageImpl#getbegin()
   * @generated
   */
  int BEGIN = 1;

  /**
   * The feature id for the '<em><b>Fault</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEGIN__FAULT = 0;

  /**
   * The number of structural features of the '<em>begin</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEGIN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.osarenogae.fta.faultTree.impl.IntermediateEventDefinitionImpl <em>Intermediate Event Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.osarenogae.fta.faultTree.impl.IntermediateEventDefinitionImpl
   * @see org.osarenogae.fta.faultTree.impl.FaultTreePackageImpl#getIntermediateEventDefinition()
   * @generated
   */
  int INTERMEDIATE_EVENT_DEFINITION = 2;

  /**
   * The feature id for the '<em><b>Fault</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERMEDIATE_EVENT_DEFINITION__FAULT = BEGIN__FAULT;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERMEDIATE_EVENT_DEFINITION__NAME = BEGIN_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERMEDIATE_EVENT_DEFINITION__DESCRIPTION = BEGIN_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERMEDIATE_EVENT_DEFINITION__VALUE = BEGIN_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Intermediate Event Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERMEDIATE_EVENT_DEFINITION_FEATURE_COUNT = BEGIN_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.osarenogae.fta.faultTree.impl.TreeImpl <em>Tree</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.osarenogae.fta.faultTree.impl.TreeImpl
   * @see org.osarenogae.fta.faultTree.impl.FaultTreePackageImpl#getTree()
   * @generated
   */
  int TREE = 3;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREE__LEFT = 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREE__RIGHT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREE__NAME = 2;

  /**
   * The number of structural features of the '<em>Tree</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.osarenogae.fta.faultTree.impl.IntermediateEventImpl <em>Intermediate Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.osarenogae.fta.faultTree.impl.IntermediateEventImpl
   * @see org.osarenogae.fta.faultTree.impl.FaultTreePackageImpl#getIntermediateEvent()
   * @generated
   */
  int INTERMEDIATE_EVENT = 4;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERMEDIATE_EVENT__LEFT = TREE__LEFT;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERMEDIATE_EVENT__RIGHT = TREE__RIGHT;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERMEDIATE_EVENT__NAME = TREE__NAME;

  /**
   * The number of structural features of the '<em>Intermediate Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERMEDIATE_EVENT_FEATURE_COUNT = TREE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.osarenogae.fta.faultTree.impl.BasicEventImpl <em>Basic Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.osarenogae.fta.faultTree.impl.BasicEventImpl
   * @see org.osarenogae.fta.faultTree.impl.FaultTreePackageImpl#getBasicEvent()
   * @generated
   */
  int BASIC_EVENT = 5;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASIC_EVENT__LEFT = TREE__LEFT;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASIC_EVENT__RIGHT = TREE__RIGHT;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASIC_EVENT__NAME = TREE__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASIC_EVENT__DESCRIPTION = TREE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Basic Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASIC_EVENT_FEATURE_COUNT = TREE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.osarenogae.fta.faultTree.impl.ConditionalEventImpl <em>Conditional Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.osarenogae.fta.faultTree.impl.ConditionalEventImpl
   * @see org.osarenogae.fta.faultTree.impl.FaultTreePackageImpl#getConditionalEvent()
   * @generated
   */
  int CONDITIONAL_EVENT = 6;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_EVENT__LEFT = TREE__LEFT;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_EVENT__RIGHT = TREE__RIGHT;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_EVENT__NAME = TREE__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_EVENT__DESCRIPTION = TREE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Conditional Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_EVENT_FEATURE_COUNT = TREE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.osarenogae.fta.faultTree.impl.ExternalEventImpl <em>External Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.osarenogae.fta.faultTree.impl.ExternalEventImpl
   * @see org.osarenogae.fta.faultTree.impl.FaultTreePackageImpl#getExternalEvent()
   * @generated
   */
  int EXTERNAL_EVENT = 7;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTERNAL_EVENT__LEFT = TREE__LEFT;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTERNAL_EVENT__RIGHT = TREE__RIGHT;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTERNAL_EVENT__NAME = TREE__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTERNAL_EVENT__DESCRIPTION = TREE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>External Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTERNAL_EVENT_FEATURE_COUNT = TREE_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.osarenogae.fta.faultTree.FaultTreeModel <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.osarenogae.fta.faultTree.FaultTreeModel
   * @generated
   */
  EClass getFaultTreeModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.osarenogae.fta.faultTree.FaultTreeModel#getFaultTree <em>Fault Tree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fault Tree</em>'.
   * @see org.osarenogae.fta.faultTree.FaultTreeModel#getFaultTree()
   * @see #getFaultTreeModel()
   * @generated
   */
  EReference getFaultTreeModel_FaultTree();

  /**
   * Returns the meta object for class '{@link org.osarenogae.fta.faultTree.begin <em>begin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>begin</em>'.
   * @see org.osarenogae.fta.faultTree.begin
   * @generated
   */
  EClass getbegin();

  /**
   * Returns the meta object for the containment reference list '{@link org.osarenogae.fta.faultTree.begin#getFault <em>Fault</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fault</em>'.
   * @see org.osarenogae.fta.faultTree.begin#getFault()
   * @see #getbegin()
   * @generated
   */
  EReference getbegin_Fault();

  /**
   * Returns the meta object for class '{@link org.osarenogae.fta.faultTree.IntermediateEventDefinition <em>Intermediate Event Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Intermediate Event Definition</em>'.
   * @see org.osarenogae.fta.faultTree.IntermediateEventDefinition
   * @generated
   */
  EClass getIntermediateEventDefinition();

  /**
   * Returns the meta object for the reference '{@link org.osarenogae.fta.faultTree.IntermediateEventDefinition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see org.osarenogae.fta.faultTree.IntermediateEventDefinition#getName()
   * @see #getIntermediateEventDefinition()
   * @generated
   */
  EReference getIntermediateEventDefinition_Name();

  /**
   * Returns the meta object for the attribute '{@link org.osarenogae.fta.faultTree.IntermediateEventDefinition#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.osarenogae.fta.faultTree.IntermediateEventDefinition#getDescription()
   * @see #getIntermediateEventDefinition()
   * @generated
   */
  EAttribute getIntermediateEventDefinition_Description();

  /**
   * Returns the meta object for the containment reference '{@link org.osarenogae.fta.faultTree.IntermediateEventDefinition#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.osarenogae.fta.faultTree.IntermediateEventDefinition#getValue()
   * @see #getIntermediateEventDefinition()
   * @generated
   */
  EReference getIntermediateEventDefinition_Value();

  /**
   * Returns the meta object for class '{@link org.osarenogae.fta.faultTree.Tree <em>Tree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tree</em>'.
   * @see org.osarenogae.fta.faultTree.Tree
   * @generated
   */
  EClass getTree();

  /**
   * Returns the meta object for the containment reference '{@link org.osarenogae.fta.faultTree.Tree#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.osarenogae.fta.faultTree.Tree#getLeft()
   * @see #getTree()
   * @generated
   */
  EReference getTree_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.osarenogae.fta.faultTree.Tree#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.osarenogae.fta.faultTree.Tree#getRight()
   * @see #getTree()
   * @generated
   */
  EReference getTree_Right();

  /**
   * Returns the meta object for the attribute '{@link org.osarenogae.fta.faultTree.Tree#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.osarenogae.fta.faultTree.Tree#getName()
   * @see #getTree()
   * @generated
   */
  EAttribute getTree_Name();

  /**
   * Returns the meta object for class '{@link org.osarenogae.fta.faultTree.IntermediateEvent <em>Intermediate Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Intermediate Event</em>'.
   * @see org.osarenogae.fta.faultTree.IntermediateEvent
   * @generated
   */
  EClass getIntermediateEvent();

  /**
   * Returns the meta object for class '{@link org.osarenogae.fta.faultTree.BasicEvent <em>Basic Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Basic Event</em>'.
   * @see org.osarenogae.fta.faultTree.BasicEvent
   * @generated
   */
  EClass getBasicEvent();

  /**
   * Returns the meta object for the attribute '{@link org.osarenogae.fta.faultTree.BasicEvent#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.osarenogae.fta.faultTree.BasicEvent#getDescription()
   * @see #getBasicEvent()
   * @generated
   */
  EAttribute getBasicEvent_Description();

  /**
   * Returns the meta object for class '{@link org.osarenogae.fta.faultTree.ConditionalEvent <em>Conditional Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Conditional Event</em>'.
   * @see org.osarenogae.fta.faultTree.ConditionalEvent
   * @generated
   */
  EClass getConditionalEvent();

  /**
   * Returns the meta object for the attribute '{@link org.osarenogae.fta.faultTree.ConditionalEvent#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.osarenogae.fta.faultTree.ConditionalEvent#getDescription()
   * @see #getConditionalEvent()
   * @generated
   */
  EAttribute getConditionalEvent_Description();

  /**
   * Returns the meta object for class '{@link org.osarenogae.fta.faultTree.ExternalEvent <em>External Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>External Event</em>'.
   * @see org.osarenogae.fta.faultTree.ExternalEvent
   * @generated
   */
  EClass getExternalEvent();

  /**
   * Returns the meta object for the attribute '{@link org.osarenogae.fta.faultTree.ExternalEvent#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.osarenogae.fta.faultTree.ExternalEvent#getDescription()
   * @see #getExternalEvent()
   * @generated
   */
  EAttribute getExternalEvent_Description();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  FaultTreeFactory getFaultTreeFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.osarenogae.fta.faultTree.impl.FaultTreeModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.osarenogae.fta.faultTree.impl.FaultTreeModelImpl
     * @see org.osarenogae.fta.faultTree.impl.FaultTreePackageImpl#getFaultTreeModel()
     * @generated
     */
    EClass FAULT_TREE_MODEL = eINSTANCE.getFaultTreeModel();

    /**
     * The meta object literal for the '<em><b>Fault Tree</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FAULT_TREE_MODEL__FAULT_TREE = eINSTANCE.getFaultTreeModel_FaultTree();

    /**
     * The meta object literal for the '{@link org.osarenogae.fta.faultTree.impl.beginImpl <em>begin</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.osarenogae.fta.faultTree.impl.beginImpl
     * @see org.osarenogae.fta.faultTree.impl.FaultTreePackageImpl#getbegin()
     * @generated
     */
    EClass BEGIN = eINSTANCE.getbegin();

    /**
     * The meta object literal for the '<em><b>Fault</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BEGIN__FAULT = eINSTANCE.getbegin_Fault();

    /**
     * The meta object literal for the '{@link org.osarenogae.fta.faultTree.impl.IntermediateEventDefinitionImpl <em>Intermediate Event Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.osarenogae.fta.faultTree.impl.IntermediateEventDefinitionImpl
     * @see org.osarenogae.fta.faultTree.impl.FaultTreePackageImpl#getIntermediateEventDefinition()
     * @generated
     */
    EClass INTERMEDIATE_EVENT_DEFINITION = eINSTANCE.getIntermediateEventDefinition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERMEDIATE_EVENT_DEFINITION__NAME = eINSTANCE.getIntermediateEventDefinition_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTERMEDIATE_EVENT_DEFINITION__DESCRIPTION = eINSTANCE.getIntermediateEventDefinition_Description();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERMEDIATE_EVENT_DEFINITION__VALUE = eINSTANCE.getIntermediateEventDefinition_Value();

    /**
     * The meta object literal for the '{@link org.osarenogae.fta.faultTree.impl.TreeImpl <em>Tree</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.osarenogae.fta.faultTree.impl.TreeImpl
     * @see org.osarenogae.fta.faultTree.impl.FaultTreePackageImpl#getTree()
     * @generated
     */
    EClass TREE = eINSTANCE.getTree();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TREE__LEFT = eINSTANCE.getTree_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TREE__RIGHT = eINSTANCE.getTree_Right();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TREE__NAME = eINSTANCE.getTree_Name();

    /**
     * The meta object literal for the '{@link org.osarenogae.fta.faultTree.impl.IntermediateEventImpl <em>Intermediate Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.osarenogae.fta.faultTree.impl.IntermediateEventImpl
     * @see org.osarenogae.fta.faultTree.impl.FaultTreePackageImpl#getIntermediateEvent()
     * @generated
     */
    EClass INTERMEDIATE_EVENT = eINSTANCE.getIntermediateEvent();

    /**
     * The meta object literal for the '{@link org.osarenogae.fta.faultTree.impl.BasicEventImpl <em>Basic Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.osarenogae.fta.faultTree.impl.BasicEventImpl
     * @see org.osarenogae.fta.faultTree.impl.FaultTreePackageImpl#getBasicEvent()
     * @generated
     */
    EClass BASIC_EVENT = eINSTANCE.getBasicEvent();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BASIC_EVENT__DESCRIPTION = eINSTANCE.getBasicEvent_Description();

    /**
     * The meta object literal for the '{@link org.osarenogae.fta.faultTree.impl.ConditionalEventImpl <em>Conditional Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.osarenogae.fta.faultTree.impl.ConditionalEventImpl
     * @see org.osarenogae.fta.faultTree.impl.FaultTreePackageImpl#getConditionalEvent()
     * @generated
     */
    EClass CONDITIONAL_EVENT = eINSTANCE.getConditionalEvent();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITIONAL_EVENT__DESCRIPTION = eINSTANCE.getConditionalEvent_Description();

    /**
     * The meta object literal for the '{@link org.osarenogae.fta.faultTree.impl.ExternalEventImpl <em>External Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.osarenogae.fta.faultTree.impl.ExternalEventImpl
     * @see org.osarenogae.fta.faultTree.impl.FaultTreePackageImpl#getExternalEvent()
     * @generated
     */
    EClass EXTERNAL_EVENT = eINSTANCE.getExternalEvent();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXTERNAL_EVENT__DESCRIPTION = eINSTANCE.getExternalEvent_Description();

  }

} //FaultTreePackage
