/**
 * generated by Xtext 2.25.0
 */
package org.osarenogae.fta.faultTree;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.osarenogae.fta.faultTree.FaultTreeModel#getFaultTree <em>Fault Tree</em>}</li>
 * </ul>
 *
 * @see org.osarenogae.fta.faultTree.FaultTreePackage#getFaultTreeModel()
 * @model
 * @generated
 */
public interface FaultTreeModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Fault Tree</b></em>' containment reference list.
   * The list contents are of type {@link org.osarenogae.fta.faultTree.begin}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fault Tree</em>' containment reference list.
   * @see org.osarenogae.fta.faultTree.FaultTreePackage#getFaultTreeModel_FaultTree()
   * @model containment="true"
   * @generated
   */
  EList<begin> getFaultTree();

} // FaultTreeModel
