/**
 * generated by Xtext 2.25.0
 */
package org.osarenogae.fta.faultTree;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Intermediate Event</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.osarenogae.fta.faultTree.FaultTreePackage#getIntermediateEvent()
 * @model
 * @generated
 */
public interface IntermediateEvent extends Tree
{
} // IntermediateEvent
