/**
 * generated by Xtext 2.25.0
 */
package org.osarenogae.fta.faultTree;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Intermediate Event Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.osarenogae.fta.faultTree.IntermediateEventDefinition#getName <em>Name</em>}</li>
 *   <li>{@link org.osarenogae.fta.faultTree.IntermediateEventDefinition#getDescription <em>Description</em>}</li>
 *   <li>{@link org.osarenogae.fta.faultTree.IntermediateEventDefinition#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.osarenogae.fta.faultTree.FaultTreePackage#getIntermediateEventDefinition()
 * @model
 * @generated
 */
public interface IntermediateEventDefinition extends begin
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(IntermediateEvent)
   * @see org.osarenogae.fta.faultTree.FaultTreePackage#getIntermediateEventDefinition_Name()
   * @model
   * @generated
   */
  IntermediateEvent getName();

  /**
   * Sets the value of the '{@link org.osarenogae.fta.faultTree.IntermediateEventDefinition#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(IntermediateEvent value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.osarenogae.fta.faultTree.FaultTreePackage#getIntermediateEventDefinition_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.osarenogae.fta.faultTree.IntermediateEventDefinition#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(Tree)
   * @see org.osarenogae.fta.faultTree.FaultTreePackage#getIntermediateEventDefinition_Value()
   * @model containment="true"
   * @generated
   */
  Tree getValue();

  /**
   * Sets the value of the '{@link org.osarenogae.fta.faultTree.IntermediateEventDefinition#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Tree value);

} // IntermediateEventDefinition
