/**
 * generated by Xtext 2.25.0
 */
package org.osarenogae.fta.faultTree;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tree</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.osarenogae.fta.faultTree.Tree#getLeft <em>Left</em>}</li>
 *   <li>{@link org.osarenogae.fta.faultTree.Tree#getRight <em>Right</em>}</li>
 *   <li>{@link org.osarenogae.fta.faultTree.Tree#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.osarenogae.fta.faultTree.FaultTreePackage#getTree()
 * @model
 * @generated
 */
public interface Tree extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(Tree)
   * @see org.osarenogae.fta.faultTree.FaultTreePackage#getTree_Left()
   * @model containment="true"
   * @generated
   */
  Tree getLeft();

  /**
   * Sets the value of the '{@link org.osarenogae.fta.faultTree.Tree#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(Tree value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(Tree)
   * @see org.osarenogae.fta.faultTree.FaultTreePackage#getTree_Right()
   * @model containment="true"
   * @generated
   */
  Tree getRight();

  /**
   * Sets the value of the '{@link org.osarenogae.fta.faultTree.Tree#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(Tree value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.osarenogae.fta.faultTree.FaultTreePackage#getTree_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.osarenogae.fta.faultTree.Tree#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // Tree
