/*
 * generated by Xtext 2.25.0
 */
package org.osarenogae.fta;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class FaultTreeStandaloneSetup extends FaultTreeStandaloneSetupGenerated {

	public static void doSetup() {
		new FaultTreeStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
