/*
 * generated by Xtext 2.25.0
 */
package org.osarenogae.fta.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFaultTreeScopeProvider extends DelegatingScopeProvider {
}
