/**
 * generated by Xtext 2.25.0
 */
package org.osarenogae.fta.faultTree.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.osarenogae.fta.faultTree.FaultTreePackage;
import org.osarenogae.fta.faultTree.Tree;
import org.osarenogae.fta.faultTree.begin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>begin</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.osarenogae.fta.faultTree.impl.beginImpl#getFault <em>Fault</em>}</li>
 * </ul>
 *
 * @generated
 */
public class beginImpl extends MinimalEObjectImpl.Container implements begin
{
  /**
   * The cached value of the '{@link #getFault() <em>Fault</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFault()
   * @generated
   * @ordered
   */
  protected EList<Tree> fault;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected beginImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FaultTreePackage.Literals.BEGIN;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Tree> getFault()
  {
    if (fault == null)
    {
      fault = new EObjectContainmentEList<Tree>(Tree.class, this, FaultTreePackage.BEGIN__FAULT);
    }
    return fault;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FaultTreePackage.BEGIN__FAULT:
        return ((InternalEList<?>)getFault()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FaultTreePackage.BEGIN__FAULT:
        return getFault();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FaultTreePackage.BEGIN__FAULT:
        getFault().clear();
        getFault().addAll((Collection<? extends Tree>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FaultTreePackage.BEGIN__FAULT:
        getFault().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FaultTreePackage.BEGIN__FAULT:
        return fault != null && !fault.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //beginImpl
