/**
 * generated by Xtext 2.25.0
 */
package org.osarenogae.fta.faultTree.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.osarenogae.fta.faultTree.FaultTreeModel;
import org.osarenogae.fta.faultTree.FaultTreePackage;
import org.osarenogae.fta.faultTree.begin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.osarenogae.fta.faultTree.impl.FaultTreeModelImpl#getFaultTree <em>Fault Tree</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FaultTreeModelImpl extends MinimalEObjectImpl.Container implements FaultTreeModel
{
  /**
   * The cached value of the '{@link #getFaultTree() <em>Fault Tree</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFaultTree()
   * @generated
   * @ordered
   */
  protected EList<begin> faultTree;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FaultTreeModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FaultTreePackage.Literals.FAULT_TREE_MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<begin> getFaultTree()
  {
    if (faultTree == null)
    {
      faultTree = new EObjectContainmentEList<begin>(begin.class, this, FaultTreePackage.FAULT_TREE_MODEL__FAULT_TREE);
    }
    return faultTree;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FaultTreePackage.FAULT_TREE_MODEL__FAULT_TREE:
        return ((InternalEList<?>)getFaultTree()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FaultTreePackage.FAULT_TREE_MODEL__FAULT_TREE:
        return getFaultTree();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FaultTreePackage.FAULT_TREE_MODEL__FAULT_TREE:
        getFaultTree().clear();
        getFaultTree().addAll((Collection<? extends begin>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FaultTreePackage.FAULT_TREE_MODEL__FAULT_TREE:
        getFaultTree().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FaultTreePackage.FAULT_TREE_MODEL__FAULT_TREE:
        return faultTree != null && !faultTree.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //FaultTreeModelImpl
