/**
 * generated by Xtext 2.25.0
 */
package org.osarenogae.fta.faultTree.impl;

import org.eclipse.emf.ecore.EClass;

import org.osarenogae.fta.faultTree.FaultTreePackage;
import org.osarenogae.fta.faultTree.IntermediateEvent;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Intermediate Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IntermediateEventImpl extends TreeImpl implements IntermediateEvent
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IntermediateEventImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FaultTreePackage.Literals.INTERMEDIATE_EVENT;
  }

} //IntermediateEventImpl
