/*
 * generated by Xtext 2.25.0
 */
package org.osarenogae.fta.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.osarenogae.fta.FaultTreeRuntimeModule;
import org.osarenogae.fta.FaultTreeStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class FaultTreeIdeSetup extends FaultTreeStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FaultTreeRuntimeModule(), new FaultTreeIdeModule()));
	}
	
}
