/*
 * generated by Xtext 2.25.0
 */
package org.osarenogae.fta.ide;


/**
 * Use this class to register ide components.
 */
public class FaultTreeIdeModule extends AbstractFaultTreeIdeModule {
}
