/*
 * generated by Xtext 2.25.0
 */
package org.osarenogae.fta.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osarenogae.fta.ui.internal.FtaActivator;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FaultTreeExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(FtaActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		FtaActivator activator = FtaActivator.getInstance();
		return activator != null ? activator.getInjector(FtaActivator.ORG_OSARENOGAE_FTA_FAULTTREE) : null;
	}

}
