/*
 * generated by Xtext 2.25.0
 */
package org.osarenogae.fta.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.osarenogae.fta.parser.antlr.internal.InternalFaultTreeParser;
import org.osarenogae.fta.services.FaultTreeGrammarAccess;

public class FaultTreeParser extends AbstractAntlrParser {

	@Inject
	private FaultTreeGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFaultTreeParser createParser(XtextTokenStream stream) {
		return new InternalFaultTreeParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "FaultTreeModel";
	}

	public FaultTreeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FaultTreeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
