/*
 * generated by Xtext 2.25.0
 */
package org.osarenogae.fta.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class FaultTreeAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/osarenogae/fta/parser/antlr/internal/InternalFaultTree.tokens");
	}
}
