/*
 * generated by Xtext 2.25.0
 */
package org.osarenogae.fta.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class FaultTreeUiModule extends AbstractFaultTreeUiModule {

	public FaultTreeUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
